# Generated by Django 4.0.1 on 2022-02-01 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_dmission', models.DateField(default=datetime.date.today)),
                ('guardian', models.CharField(max_length=100)),
                ('stream_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.stream')),
            ],
        ),
    ]
