# Generated by Django 4.0.1 on 2022-02-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_dmission',
            new_name='date_of_admission',
        ),
    ]
